sudo: false
language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - tip

before_script:
  - go get -t -v

script:
  - go test -v -test.bench=.* -timeout=100000

